services:
  - type: web
    name: rag-search-api
    env: python
    repo: https://github.com/ompattanayak/IITM_FASTAPI/
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10

