services:
  - type: web
    name: iitm-fastapi
    env: python
    region: oregon
    plan: free
    branch: main
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    autoDeploy: true
